### ISSUE TITLE
Create custom Dictionary class

### ISSUE THREAD

**Issue by romaneo** [marikalmuk/Tasks#12]
Using the technique we talked about on the last call create a custom implementation of the Dictionary structure.

Programm requirements:
- implement the ability to ```add``` new ```pair``` of ```Key```\```Value``` (myDictionary.Add("someKey", "someValue"))
- implement retriving ```value``` by Key (myDictionary.Get("someKey"))
- impement ```validation``` if key already present in the dictionary (myDictionary.IsExist("someKey"))
- implement the ability to ```remove``` existing pair by ```Key``` (myDictionary.Remove("someKey"))

Programm recommendation:
- you can implement internal dictionary storage as List(preferred and easier) or Array

Learning materials:
- https://metanit.com/sharp/tutorial/3.12.php
- https://metanit.com/sharp/tutorial/3.38.php
- https://docs.microsoft.com/ru-ru/dotnet/csharp/programming-guide/generics/constraints-on-type-parameters
- https://metanit.com/sharp/tutorial/2.31.php (may be useful for the situation when the specified key was not found)
- https://stackoverflow.com/questions/2357410/having-to-implement-a-generic-less-than-and-greater-than-operation/2357426 (I think this link is not necessary for the current task but for general knowledge or may be used as an explanation to the demo program )

<details>
  <summary>Hint spoiler</summary>
You can implement both ```dictionary``` and ```pair``` as separate classes
<br/>\<br/>
\<br/>
\<br/>
          <details>
            <summary>CODE SPOILER HINT (OPEN IN CASE OF CRITICAL NEED)</summary>
https://pastebin.com/1LrBN6rc
</details>

**Comment by marikalmuk** [comment]
https://metanit.com/sharp/tutorial/3.36.php - Operators override 
https://app.pluralsight.com/library/courses/csharp-equality-comparisons/table-of-contents

**Comment by romaneo** [comment]
Please rename ```Class1``` and ```Class2``` according to the class names inside.
After that, merge the branch and close the issue.
