### ISSUE TITLE
Print a multiplication table for any range of numbers

### ISSUE THREAD

**Issue by romaneo** [marikalmuk/Tasks#6]
### Input data:
- start number
- end number

### Prerequisites:
- create a new branch
- create a new solution

### Programm workflow should be the next:
- enter the start number
- enter the end number
- print formatted multiplication table with row/column headers (headers marked in bold in examples for demonstration purposes)
- **_(optionally):_** use a similar approach with the infinite loop as in #5 for testing purpose

### Programm requirements:
- Use ```for``` loop

### Examples
Example 1:
start number: 0
end number: 2

&nbsp;&nbsp;&nbsp;   **0 1 2** _(<-header)_
**0** 0 0 0
**1** 0 1 2
**2** 0 2 4

Example 2:
start number: 2
end number: 4

&nbsp;&nbsp;&nbsp;**2 3 4**
**2** 4 6 8
**3** 6 9 12
**4** 8 12 16

### Learning materials:
For logic:
- https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/keywords/for
- https://docs.microsoft.com/ru-ru/dotnet/csharp/tutorials/intro-to-csharp/branches-and-loops-local#created-nested-loops
- https://kodify.net/csharp/loop/nested-loop/
- **_(read this)_** https://stackoverflow.com/questions/101070/what-is-an-ideal-variable-naming-convention-for-loop-variables

<br/>

For output:
- https://metanit.com/sharp/tutorial/7.5.php
- https://docs.microsoft.com/ru-ru/dotnet/standard/base-types/composite-formatting#alignment-component

**Comment by romaneo** [comment]
@marikalmuk, please merge this branch to main and close this issue

**Comment by marikalmuk** [comment]
> @marikalmuk, please merge this branch to main and close this issue

@romaneo , done
