### ISSUE TITLE
Create a one-dimensional array of random data and perform calculations

### ISSUE THREAD

**Issue by romaneo** [marikalmuk/Tasks#7]
Create a new program with the next features:

- enter any number greater than 10;
- initialize an empty array of int's with the number of elements specified in the previous step
- fill the array with random ```int``` data (both positive and negative)
- print all array
- perform next calculations and filters:

1. find and print the sum of all positive and negative numbers
2. find and print the index of the largest and smallest element
3. swap elements from step 2
4. print all array again
5. check if the first 10 elements are positive
6. check if the last 10 elements are negative
7. print all odd elements, multiply each element to the previous one (for the first element multiply by 1)
8. print all even elements, order them by descending
9. enter a number, multiply all elements greater than 10 by modulus (https://docs.microsoft.com/ru-ru/dotnet/api/system.math.abs?view=net-5.0)
10. check if the array contains any zeros

### General recommendation:
There are two possible solutions to the above tasks:
- using loops: for, foreach
- using LINQ

I recommend reading the documentation below and start doing this task using loops(at least the first 5 tasks).
After that, we will organize a call where we will discuss any question/difficulties regarding linq

### Additional materials:
- https://docs.microsoft.com/ru-ru/dotnet/csharp/language-reference/keywords/foreach-in
- https://metanit.com/sharp/tutorial/2.4.php
- https://professorweb.ru/my/csharp/charp_theory/level4/4_4.php
- https://stackoverflow.com/questions/2706500/how-do-i-generate-a-random-int-number
- https://docs.microsoft.com/ru-ru/dotnet/api/system.random?view=net-5.0
- https://metanit.com/sharp/tutorial/15.1.php (and all other topics from this chapter)
- https://docs.microsoft.com/ru-ru/dotnet/csharp/linq/

---
some information about IEnumerable
- https://stackoverflow.com/questions/558304/can-anyone-explain-ienumerable-and-ienumerator-to-me
- https://stackoverflow.com/questions/3014737/what-is-ienumerable-in-net
- https://github.com/MarkSFrancis/ienumerable-explained

More about linq
- https://www.csharp-examples.net/linq-aggregation-methods/
- https://dotnettutorials.net/lesson/introduction-to-linq/ 
![image](https://user-images.githubusercontent.com/6523447/110086834-8cc42600-7d9b-11eb-8164-5b1cb33c7f68.png)
![image](https://user-images.githubusercontent.com/6523447/110086855-92ba0700-7d9b-11eb-9605-bec2b21c7c02.png)
![image](https://user-images.githubusercontent.com/6523447/110086877-9a79ab80-7d9b-11eb-8977-0d7679869995.png)

**Comment by marikalmuk** [comment]
merged to main
branch Task#7 deleted
